/**
 * The plugin's own words, in two languages.
 *
 * There are two dictionaries in this directory and they are not the same thing.
 * `i18n.mjs` is the *game's* — it comes out of the Space Trader checkout with
 * the engine, it is regenerated by `npm run engine`, and it knows what a Flea
 * is called and what "Bought 3 × Water for 90 cr" says in Ukrainian. Nothing
 * here may be written into it, because the next build would throw it away.
 *
 * This is everything the *plugin* says: the panel, the buttons, the screens,
 * the refusals and the notes the model reads. That used to be English literals
 * spread through `main.mjs` and `view.mjs`, which made the Ukrainian setting a
 * half-truth — the commodity names translated and every label around them did
 * not. Keyed and moved out here, the two halves of a screen can finally be in
 * the same language.
 *
 * English is the source. A key missing from the other file falls back to it,
 * so a half-finished translation shows the parts that are done and English for
 * the rest, which is a game somebody can still play.
 */
import { en } from './locales/en.mjs';
import { uk } from './locales/uk.mjs';

/** Every language the plugin speaks, in the order the setting offers them. */
export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'uk', label: 'Українська' },
];

const TABLES = { en, uk };

/** The language in force. Module-level because it is a property of the session. */
let current = 'en';

export function setLanguage(code) {
  current = TABLES[String(code ?? '')] ? String(code) : 'en';
  return current;
}

export function language() {
  return current;
}

/**
 * How many forms a count needs, by language.
 *
 * English has two and Ukrainian has three, and the difference is not
 * decoration: "5 одиниць" and "2 одиниці" are different words, and a game that
 * writes "2 одиниц(ь)" has given up in front of the player. Space Trader counts
 * constantly — units of cargo, parsecs, credits, days — so this is not an edge
 * case here, it is most of the sentences.
 */
function pluralForm(count, code) {
  if (code === 'en') return count === 1 ? 'one' : 'other';
  const n = Math.abs(Math.floor(count));
  const mod10 = n % 10;
  const mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return 'one';
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return 'few';
  return 'many';
}

function lookup(key) {
  const table = TABLES[current] ?? en;
  // English is the fallback rather than the key, so a missing translation reads
  // as a sentence in the wrong language instead of as `panel.field.credits`.
  return table[key] ?? en[key];
}

/**
 * Fill `{name}` holes from `params`.
 *
 * A hole with nothing to put in it is left as it is rather than blanked: an
 * empty gap in a sentence looks like a bug in the game, and `{system}` looks
 * like a bug in the translation, which is what it is.
 */
function fill(template, params) {
  return String(template).replace(/\{(\w+)\}/g, (whole, name) => (params?.[name] === undefined ? whole : String(params[name])));
}

/**
 * One phrase, in the language in force.
 *
 * A value may be a string, or an object of plural forms chosen by `params.n`.
 * An unknown key returns the key itself — visible, greppable, and never an
 * empty space somebody has to guess the meaning of.
 */
export function t(key, params) {
  const entry = lookup(key);
  if (entry === undefined) return key;
  if (typeof entry === 'object') {
    const form = pluralForm(Number(params?.n) || 0, current);
    return fill(entry[form] ?? entry.other ?? entry.many ?? Object.values(entry)[0] ?? key, params);
  }
  return fill(entry, params);
}

/** Is this key translated at all? Used by the tests, and by nothing else. */
export function has(key) {
  return lookup(key) !== undefined;
}

/**
 * The words the game listens for, in the language in force and in English.
 *
 * Always English as well, and deliberately: the buttons send the phrasing of
 * the current language, but a player types what comes to hand and a small model
 * asked to relay "warp to Nyle" sometimes translates it on the way. Both should
 * work.
 */
export function patterns(key) {
  const table = TABLES[current] ?? en;
  const here = table[`re.${key}`] ?? '';
  const english = en[`re.${key}`] ?? '';
  const both = [...new Set([here, english].filter(Boolean))].join('|');
  return both ? new RegExp(both, 'i') : /(?!)/;
}

/**
 * A number with the thousands separated, in the reader's convention.
 *
 * A trader reads six-figure sums all game and `102400` is not a number anybody
 * takes in at a glance. Ukrainian groups with a space rather than a comma, so
 * this is a phrase like any other rather than a `toLocaleString('en-US')`
 * frozen into the code.
 */
export function group(value) {
  const digits = Math.round(Number(value) || 0).toString();
  const sign = digits.startsWith('-') ? '-' : '';
  const body = sign ? digits.slice(1) : digits;
  return sign + body.replace(/\B(?=(\d{3})+(?!\d))/g, t('num.thousands'));
}

/** Credits, which are written the same way everywhere they are written. */
export function credits(value) {
  return t('num.credits', { amount: group(value) });
}

/**
 * A line cut where a reader would cut it.
 *
 * The panel trims an over-long label or note to its own limit, and that lands
 * mid-word: a news body ended "though the miners are not celebratin" and a line
 * of a gunfight ended "A bounty hunter in a Hornet has come to collect ". Cut at
 * the last space instead and say so with an ellipsis. Nothing is lost by it —
 * every one of these is written out in full in the transcript, which has no
 * ceiling; this is the row that points at it.
 */
export function clip(text, limit = 120) {
  const value = String(text ?? '').trim();
  if (value.length <= limit) return value;
  const cut = value.slice(0, limit - 1);
  const space = cut.lastIndexOf(' ');
  return `${(space > limit * 0.6 ? cut.slice(0, space) : cut).replace(/[\s,;:.—-]+$/, '')}…`;
}
